[package]
name = "protoc-gen-prost"
version = "0.1.1"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "Coming soon…"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
exclude = [
    "proto"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost-build = { version = "0.9.0", default-features = false }
prost-types = { version = "0.9.0", default-features = false }
prost = { version = "0.9.0", default-features = false, features = ["std"] }
regex = { version = "1.5.5", default-features = false }

[patch.crates-io]
prost-build = { git = "https://github.com/tokio-rs/prost", branch = "master" }
prost-types = { git = "https://github.com/tokio-rs/prost", branch = "master" }
prost = { git = "https://github.com/tokio-rs/prost", branch = "master" }
