[package]
name = "protoc-gen-prost"
version = "0.1.0"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "Coming soon…"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.0"
prost-build = { version = "0.9.0", git = "https://github.com/neoeinstein/prost.git", branch = "protoc-gen-prost", default-features = false }
prost-types = { version = "0.9.0", git = "https://github.com/neoeinstein/prost.git", branch = "protoc-gen-prost", default-features = false }
prost = { version = "0.9.0", git = "https://github.com/neoeinstein/prost.git", branch = "protoc-gen-prost", default-features = false }

## Not currently required by prost
regex = { version = "1.5.4", features = ["unicode-perl"] }
