[workspace]
members = [
    "protoc-gen-prost",
    "protoc-gen-prost-crate",
    "protoc-gen-prost-serde",
    "protoc-gen-prost-validate",
    "protoc-gen-tonic",
]

[profile.release]
codegen-units = 1
lto = "fat"
debug = true
